package vision.combat.c4.ds.sample.bookmarks.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import vision.combat.c4.ds.sample.bookmarks.domain.model.Bookmark

/**
 * Room entity for a single saved bookmark — a Data-layer detail mapped to/from the
 * `:bookmarks:domain` [Bookmark] model and never *referenced* from `:bookmarks:app`.
 *
 * Public (not `internal`) purely because Kotlin does not allow a `public` member of
 * [vision.combat.c4.ds.sample.bookmarks.data.db.dao.BookmarkDao] (itself `public` so
 * `:bookmarks:app` DI can bind it) to expose an `internal` type such as
 * `Flow<List<BookmarkEntity>>`. `:bookmarks:app` never imports this type directly — only the
 * mapped [Bookmark] domain model and the opaque [BookmarkDao]/`BookmarkDatabase` handles.
 *
 * The primary key is the same `String` UUID used by the domain model (generated in
 * `BookmarkRepositoryImpl.add`), not a Room-autogenerated key, so [Bookmark.id] stays untouched.
 */
@Entity(tableName = "bookmarks")
public data class BookmarkEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,
    @ColumnInfo(name = "label")
    val label: String,
    @ColumnInfo(name = "target")
    val target: String,
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),
)

internal fun BookmarkEntity.toDomain(): Bookmark = Bookmark(id = id, label = label, target = target)

internal fun Bookmark.toEntity(): BookmarkEntity = BookmarkEntity(id = id, label = label, target = target)
