package vision.combat.c4.ds.sample.bookmarks.data

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import vision.combat.c4.ds.sample.bookmarks.data.db.entity.toDomain
import vision.combat.c4.ds.sample.bookmarks.data.db.entity.toEntity
import vision.combat.c4.ds.sample.bookmarks.domain.model.Bookmark

/**
 * Pure-JVM coverage for the [Bookmark] <-> `BookmarkEntity` mappers. Room DAO bodies are
 * generated by the compiler and are not tested directly (see
 * `docs/testing/testing-your-tool.md`); the mapper round-trip is the piece of hand-written
 * logic worth asserting.
 */
class BookmarkMappersTest {

    @Test
    fun `toEntity then toDomain round-trips id, label and target`() {
        val bookmark = Bookmark(id = "bookmark-1", label = "Home", target = "vision.combat.c4.ds.sample.bookmarks/home")

        val roundTripped = bookmark.toEntity().toDomain()

        assertEquals(bookmark, roundTripped)
    }
}
